#!/usr/bin/env python3
"""Iteration 624: source-vs-native functional object-type audit.

Goal: determine whether the remaining Iter621/622 N_native can be fixed by a
pure Legendre-transform sign/factor alone, or whether the two frozen objects are
functionally different and require an explicit measurement-level bridge.

No Candidate/comparator values are used.
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[2]

iter147 = (ROOT / "candidate_gravity/C5_RETARDED_EMBEDDING_ITERATION147.md").read_text()
iter149 = (ROOT / "candidate_gravity/C5_SOURCE_COMPLETED_PROTOCOL_ITERATION149.md").read_text()
iter590 = (ROOT / "analysis/source_cubic_response_completeness_iteration590.py").read_text()
iter616 = (ROOT / "candidate_gravity/results/iteration616_native_binding_endpoint_amputation_and_normalization_audit.json").read_text()

failures = []

native_tokens = [
    "chi2R_A;BC = - G_R,AA' V^A'_{B'C'} G_R,B'B G_R,C'C",
    "chi2R_A;BC = - G_R(p) Gamma3 G_R(q) G_R(r)",
]
if not any(t in iter147 or t in iter149 for t in native_tokens):
    failures.append("native retarded Gamma3 object definition missing")

if "universal_identity':'d_abc G = -G Kabc G + sum_6(G Ki G Kjk G) - sum_6(G Ki G Kj G Kk G), G=K^-1'" not in iter590:
    # tolerate source formatting drift by checking the core formula fragments
    if "d_abc G = -G Kabc G" not in iter590 or "G=K^-1" not in iter590:
        failures.append("MSSC scalar-propagator metric-response identity missing")

if "S_amp^(3)=K0_out*(d_abc G)*K0_in" not in iter616:
    failures.append("Iter616 scalar endpoint amputation definition missing")

passed = not failures

result = {
    "iteration": 624,
    "date": "2026-09-08",
    "scientific_gate_pass": passed,
    "candidate_residual": False,
    "classification": (
        "PASS_ITER624_SOURCE_VS_NATIVE_FUNCTIONAL_OBJECT_TYPE_AUDIT__LEGENDRE_SIGN_ALONE_CANNOT_FIX_N_NATIVE__MEASUREMENT_LEVEL_BRIDGE_REQUIRED_NON_RESIDUAL"
        if passed else
        "BLOCKED_ITER624_FUNCTIONAL_OBJECT_AUTHORITY_DRIFT"
    ),
    "native_object": "gravitational retarded/1PI cubic response: chi2R = - G_R Gamma3 G_R G_R",
    "source_object": "third background-metric derivative of the MSSC scalar propagator G_phi=K_phi[g]^-1, then scalar-endpoint amputation",
    "exact_distinction": (
        "the source object carries two external matter endpoints and metric insertions generated by the matter kernel; native Gamma3 is a pure gravitational 1PI vertex/retarded response object. They are not the same functional derivative and no generic W<->Gamma Legendre identity equates them."
    ),
    "derived_consequence": (
        "N_native cannot be fixed merely by choosing the conventional i/sign of W or Gamma. A concrete combined matter+gravity measurement functional must specify how the MSSC probe contracts with gravitational propagators/vertices and contacts in the frozen observable."
    ),
    "required_bridge_minimum": [
        "one combined CTP/in-in generating functional with both metric/gravity and scalar-probe sources",
        "explicit identification of the measured connected scalar-probe observable",
        "explicit amputation/projection rule from that observable to the native Gamma3/Iter582 coordinate",
        "all kappa/factorial/i/sign factors derived before consulting Candidate/comparator values",
        "preservation of Iter618/619 six-root projective ratios"
    ],
    "forbidden_shortcuts": [
        "N_native=+i from Iter338 alone",
        "N_native=-1 from chi2R=-G_R Gamma3 G_R G_R alone",
        "treating the MSSC scalar response as identical to pure gravitational Gamma3",
        "fitting N_native to Iter582/Iter615 values"
    ],
    "failures": failures,
    "MODEL_READINESS": "24%",
    "next_gate": "freeze a combined matter+gravity CTP measurement-level bridge and derive its tree/1PI normalization before any native projection"
}
print(json.dumps(result, indent=2, sort_keys=True))
if failures:
    raise SystemExit(2)
