#!/usr/bin/env python3
"""Inventory downloaded mass-support raw artifact payloads fail-closed.

Input directory must contain ZIP-expanded directories named by artifact id and
an expected_sources.json generated by the workflow.  This gate verifies exact
artifact ZIP SHA-256 before extraction (workflow), then inventories JSON files
and detects candidate row arrays without interpreting them as F(u,v).

No numerical assembly, no support reordering, no regeneration, no promotion.
"""
from __future__ import annotations
import json, hashlib, math
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
RAW=ROOT/'raw_payloads'
EXP=json.loads((RAW/'expected_sources.json').read_text())


def json_files(d):
    return sorted(p for p in d.rglob('*.json') if p.is_file())

def walk_lists(obj, path='$'):
    out=[]
    if isinstance(obj,list):
        out.append((path,len(obj),obj))
        for i,x in enumerate(obj[:3]):
            out.extend(walk_lists(x,f'{path}[{i}]'))
    elif isinstance(obj,dict):
        for k,v in obj.items():
            out.extend(walk_lists(v,f'{path}.{k}'))
    return out

def finiteish(x):
    if isinstance(x,(int,float)): return math.isfinite(float(x))
    if isinstance(x,str):
        try: return math.isfinite(float(x))
        except Exception: return True
    if isinstance(x,list): return all(finiteish(v) for v in x)
    if isinstance(x,dict): return all(finiteish(v) for v in x.values())
    return True

reports=[]; all_downloaded=True; all_json=True; all_expected_row_candidate=True
for src in EXP['sources']:
    aid=str(src['artifact_id']); d=RAW/aid
    rec={k:src[k] for k in src}
    rec['extracted_dir_exists']=d.is_dir()
    all_downloaded &= d.is_dir()
    files=json_files(d) if d.is_dir() else []
    rec['json_file_count']=len(files)
    rec['json_files']=[]
    expected_rows=int(src['expected_rows'])
    found_expected=False
    for p in files:
        try:
            raw=p.read_bytes(); obj=json.loads(raw)
            lists=walk_lists(obj)
            candidates=[]
            for path,n,val in lists:
                if n in (16,32,48,80) or n==expected_rows:
                    sample=val[0] if val else None
                    candidates.append({'path':path,'length':n,
                                       'first_element_type':type(sample).__name__ if sample is not None else None,
                                       'first_element_keys':sorted(sample.keys()) if isinstance(sample,dict) else None})
                    if n==expected_rows: found_expected=True
            rec['json_files'].append({
                'path':str(p.relative_to(d)),
                'sha256':hashlib.sha256(raw).hexdigest(),
                'top_level_type':type(obj).__name__,
                'top_level_keys':sorted(obj.keys()) if isinstance(obj,dict) else None,
                'all_values_finite_or_non_numeric':finiteish(obj),
                'candidate_lists':candidates,
            })
        except Exception as e:
            rec['json_files'].append({'path':str(p.relative_to(d)),'parse_error':repr(e)})
            all_json=False
    rec['expected_row_count_candidate_found']=found_expected
    all_expected_row_candidate &= found_expected
    reports.append(rec)

passed=bool(all_downloaded and all_json and all_expected_row_candidate and len(reports)==len(EXP['sources']))
out={
 'stage':'POST479_MASS_SUPPORT_RAW_PAYLOAD_INVENTORY__COLLISION_SAFE',
 'classification':('PASS_ALL_CURRENT_CERTIFIED_RAW_ARTIFACTS_DOWNLOADABLE_AND_PAYLOAD_ROW_ARRAYS_LOCATED__NON_PROMOTING' if passed else 'BLOCKED_RAW_PAYLOAD_INVENTORY__NON_PROMOTING'),
 'scientific_gate_pass':passed,
 'promotes_physical_coordinate':False,
 'MODEL_READINESS':'24%',
 'readiness_change_pp':0,
 'scope':{'artifact_sources':len(EXP['sources']),'certified_distinct_coordinates':11,'certified_occurrences':15,
          'note':'rank10 uses two disjoint-z artifacts; therefore source count is 12'},
 'observed':{
    'all_extracted':all_downloaded,
    'all_json_parseable':all_json,
    'all_expected_row_count_candidates_found':all_expected_row_candidate,
    'source_reports':reports,
 },
 'interpretation':[
   'This gate proves current raw artifacts remain downloadable and locates JSON list payloads with the expected certified row counts.',
   'It intentionally does not yet assign semantic field meanings to candidate lists; a subsequent schema-binding verifier must bind z, phi, precision and radial-limit fields before assembly.',
   'Artifact ZIP digest verification is performed before this script by the workflow and is part of the raw authority contract.',
 ],
 'next_gate_if_pass':'freeze exact payload schema bindings for z/phi/MP80/MP120 radial-limit rows and verify coordinate/z/phi uniqueness plus 80-row or 48+32 composite coverage; do not assemble F until all 28 coordinates are locally certified',
 'next_gate_if_blocked':'localize missing/expired/digest-mismatched artifact or schema drift; never regenerate as provenance substitute',
 'guardrails':['NO_FUV_EVALUATION','NO_ACTIVE_RANK11_DUPLICATION','NO_SUPPORT_REORDERING','NO_UV_SWAP_DEDUPLICATION','NO_REGENERATION_AS_PROVENANCE_SUBSTITUTE','NO_THRESHOLD_CHANGE','NO_PHYSICAL_DS_PROMOTION','NO_ANSATZ003','NO_FISHER_RESOURCES']
}
print(json.dumps(out,indent=2,sort_keys=True))
if not passed: raise SystemExit(2)
