#!/usr/bin/env python3
"""Post-477 frozen-basis continuous-MP geometry audit for unresolved index 2.

Purpose
-------
The current direct-parent MP mass-node chain evaluates Q0/Q1/A1 in mpmath, but
its cut momentum p is generated by Iteration-431/407 NumPy/math kinematics.
This collision-safe diagnostic reconstructs the scalar cut kinematics and all
sample momenta in MP80/MP120 while treating the already-frozen source vectors
(a,q,c,e1,e2,e3,ETA) as exact decimal inputs.

This closes only arithmetic downstream of the frozen basis/source vectors.  It
does NOT certify arbitrary-precision reconstruction of the basis itself, does
not replace the active Iteration-455 queue, and cannot promote physical D_s.
"""
from __future__ import annotations
import contextlib, io, json, math, time
from pathlib import Path
import numpy as np
import mpmath as mp

ROOT = Path(__file__).resolve().parent
MP_LEVELS = (80, 120)
MP_LIMIT = mp.mpf('1e-30')
ASSEMBLY_REFERENCE = mp.mpf('2e-6')
PHYSICAL_REFERENCE = mp.mpf('2e-5')
RADIAL_HS = (2.0e-3, 1.0e-3, 5.0e-4)
Z_SAMPLES = (-0.86, -0.43, 0.0, 0.43, 0.86)
NPHI = 16

# Load the specialized index-2/class-3 Iteration-431 source only through the
# pre-execution boundary.  This is source/provenance binding, not authority
# promotion; 431 is known to be a collision-created diagnostic identifier.
p431 = ROOT / 'iteration431_channel2_cut_kinematic_h1_sensitivity.py'
s431 = p431.read_text()
marker = 'records=[]; max_delta=0.0; max_raderr=0.0'
if s431.count(marker) != 1:
    raise SystemExit(('iteration431_boundary_drift', s431.count(marker)))
C = {'__name__': 'post477_geometry_parent431', '__file__': str(p431)}
with contextlib.redirect_stdout(io.StringIO()):
    exec(compile(s431.split(marker, 1)[0], str(p431), 'exec'), C, C)

if int(C['ch']['class_id']) != 3 or abs(float(C['q2']) + 1.0) > 1e-12:
    raise SystemExit(('target_identity_drift', C['ch']['class_id'], C['q2']))

ns407 = C['ns407']
a_np = np.asarray(C['a'], float)
q_np = np.asarray(C['q'], float)
e1_np = np.asarray(C['e1'], float)
e2_np = np.asarray(C['e2'], float)
e3_np = np.asarray(C['e3'], float)
c_np = np.asarray(ns407['c'], float)
ETA_np = np.asarray(C['ETA'], float)
kin_binary = C['kin']
unit_binary = C['unit_from']
affine_binary = ns407['affine_coeffs']
BASE_H = float(ns407['BASE_H'])
HALF_H = float(ns407['HALF_H'])
s_binary = float(ns407['s'])

# Preserve Iteration-455 exact source order and exact BASE/HALF overlaps.
def nodes(h):
    return (-2*h, -h, h, 2*h)
occurrences = [('BASE', u, v) for u in nodes(BASE_H) for v in nodes(BASE_H)] + \
              [('HALF', u, v) for u in nodes(HALF_H) for v in nodes(HALF_H)]
coords = []
for _, u, v in occurrences:
    if not any(abs(u-x) < 1e-18 and abs(v-y) < 1e-18 for x, y in coords):
        coords.append((u, v))
if len(occurrences) != 32 or len(coords) != 28:
    raise SystemExit(('mass_support_drift', len(occurrences), len(coords)))


def mpr(x):
    return mp.mpf(repr(float(x)))


def vec_mp(x):
    return [mpr(v) for v in np.asarray(x, float)]


def mat_mp(x):
    arr = np.asarray(x, float)
    return [[mpr(arr[i, j]) for j in range(arr.shape[1])] for i in range(arr.shape[0])]


def bilinear(x, y, eta):
    return sum(x[i] * eta[i][j] * y[j] for i in range(4) for j in range(4))


def vadd(*vs):
    return [sum(v[i] for v in vs) for i in range(4)]


def vscale(s, v):
    return [s*x for x in v]


def vneg(v):
    return [-x for x in v]


def scaled_scalar(x, y):
    return abs(x-y) / max(mp.mpf(1), abs(x), abs(y))


def scaled_vec(x, y):
    num = max(abs(x[i]-y[i]) for i in range(4))
    den = max([mp.mpf(1)] + [abs(z) for z in x] + [abs(z) for z in y])
    return num / den


def mp_geometry(u0, v0, z0, m, hrad, sign, dps):
    with mp.workdps(dps):
        a = vec_mp(a_np); q = vec_mp(q_np); c = vec_mp(c_np)
        e1 = vec_mp(e1_np); e2 = vec_mp(e2_np); e3 = vec_mp(e3_np); eta = mat_mp(ETA_np)
        u = mpr(u0); v = mpr(v0); z = mpr(z0); s = mpr(s_binary)
        lam = s*s + u*u + v*v - 2*s*u - 2*s*v - 2*u*v
        if lam <= 0:
            raise RuntimeError(('nonpositive_kallen_mp', u0, v0, mp.nstr(lam, 40)))
        alpha = -(s + u - v) / (2*s)
        rho = mp.sqrt(lam) / (2*mp.sqrt(s))
        beta = mp.sqrt(lam) / s
        phi = 2*mp.pi*mp.mpf(m)/NPHI
        rr = mp.sqrt(max(mp.mpf(0), 1-z*z))
        unit = vadd(vscale(rr*mp.cos(phi), e1), vscale(rr*mp.sin(phi), e2), vscale(z, e3))
        vec = vscale(rho, unit)
        fac = 1 + mpr(sign)*mpr(hrad)
        p = vadd(vneg(a), vscale(alpha, q), vscale(fac, vec))
        r0 = vadd(vneg(a), vscale(alpha, q), c)
        cc = bilinear(r0, r0, eta) + rho*rho
        aa = 2*rho*bilinear(r0, e3, eta)
        return {
            'alpha': alpha, 'rho': rho, 'beta': beta, 'lambda': lam,
            'p': p, 'cc': cc, 'aa': aa,
        }


def binary_geometry(u, v, z, m, hrad, sign):
    alpha, rho, beta, lam = kin_binary(u, v)
    phi = 2.0*math.pi*m/NPHI
    unit = np.asarray(unit_binary(z, phi), float)
    p = -a_np + alpha*q_np + (1.0 + sign*hrad)*rho*unit
    cc, aa = affine_binary(u, v)
    return {
        'alpha': complex(alpha), 'rho': complex(rho), 'beta': complex(beta), 'lambda': complex(lam),
        'p': np.asarray(p, float), 'cc': complex(cc), 'aa': complex(aa),
    }


def to_pair(z, dps):
    return (mp.nstr(mp.re(z), dps), mp.nstr(mp.im(z), dps))

start = time.perf_counter()
max_80_120 = mp.mpf('0')
max_binary_mp120 = mp.mpf('0')
max_binary_p_mp120 = mp.mpf('0')
max_binary_affine_mp120 = mp.mpf('0')
max_binary_beta_mp120 = mp.mpf('0')
all_finite = True
worst = None
sample_count = 0

# Scalar/affine coverage on all 28 distinct mass coordinates; point coverage on
# the exact 5z x 16phi x 3 radial-h x 2 signs parent-sampling support.
for rank, (u, v) in enumerate(coords):
    # One point is sufficient to carry scalar/affine values; z/phi/radial do not enter them.
    g80 = mp_geometry(u, v, Z_SAMPLES[0], 0, RADIAL_HS[0], +1.0, 80)
    g120 = mp_geometry(u, v, Z_SAMPLES[0], 0, RADIAL_HS[0], +1.0, 120)
    b = binary_geometry(u, v, Z_SAMPLES[0], 0, RADIAL_HS[0], +1.0)
    with mp.workdps(150):
        for key in ('alpha', 'rho', 'beta', 'lambda', 'cc', 'aa'):
            d = scaled_scalar(g80[key], g120[key]); max_80_120 = max(max_80_120, d)
            bz = mp.mpc(repr(float(np.real(b[key]))), repr(float(np.imag(b[key]))))
            db = scaled_scalar(bz, g120[key]); max_binary_mp120 = max(max_binary_mp120, db)
            if key in ('cc', 'aa'):
                max_binary_affine_mp120 = max(max_binary_affine_mp120, db)
            if key == 'beta':
                max_binary_beta_mp120 = max(max_binary_beta_mp120, db)
            all_finite = all_finite and bool(mp.isfinite(g120[key]))
    for z in Z_SAMPLES:
        for m in range(NPHI):
            for hrad in RADIAL_HS:
                for sign in (-1.0, +1.0):
                    x80 = mp_geometry(u, v, z, m, hrad, sign, 80)
                    x120 = mp_geometry(u, v, z, m, hrad, sign, 120)
                    xb = binary_geometry(u, v, z, m, hrad, sign)
                    with mp.workdps(150):
                        d = scaled_vec(x80['p'], x120['p']); max_80_120 = max(max_80_120, d)
                        bp = [mpr(t) for t in xb['p']]
                        db = scaled_vec(bp, x120['p'])
                        if db > max_binary_p_mp120:
                            max_binary_p_mp120 = db
                        if db > max_binary_mp120:
                            max_binary_mp120 = db
                            worst = {'distinct_rank': rank, 'u': u, 'v': v, 'z': z, 'phi_index': m, 'radial_h': hrad, 'radial_sign': sign, 'quantity': 'p'}
                        all_finite = all_finite and all(bool(mp.isfinite(t)) for t in x120['p'])
                    sample_count += 1

passed = bool(all_finite and max_80_120 <= MP_LIMIT and sample_count == 28*5*16*3*2)
material_assembly = bool(max_binary_mp120 > ASSEMBLY_REFERENCE)
material_physical = bool(max_binary_mp120 > PHYSICAL_REFERENCE)

out = {
    'stage': 'POST477_FROZEN_BASIS_GEOMETRY_MP_AUDIT__COLLISION_SAFE',
    'classification': ('PASS_FROZEN_BASIS_GEOMETRY_ARITHMETIC_MP80_MP120__BINARY_DRIFT_DIAGNOSTIC_ONLY_NON_PROMOTING' if passed else 'BLOCKED_FROZEN_BASIS_GEOMETRY_ARITHMETIC_MP__NON_PROMOTING'),
    'scientific_gate_pass': passed,
    'promotes_physical_coordinate': False,
    'MODEL_READINESS': '24%',
    'readiness_change_pp': 0,
    'target': {'double_double_index': 2, 'class_id': 3, 'q_squared': -1.0},
    'scope': 'ALL_28_DISTINCT_MASS_COORDS__5Z__16PHI__3_RADIAL_H__2_SIGNS__FROZEN_BINARY_SOURCE_VECTORS_RECOMPUTED_IN_MP',
    'frozen': {
        'mass_occurrences': 32,
        'distinct_mass_coordinates': 28,
        'z_samples': list(Z_SAMPLES),
        'phi_nodes': NPHI,
        'radial_hs': list(RADIAL_HS),
        'radial_signs': [-1, 1],
        'precision_digits': list(MP_LEVELS),
        'basis_source': 'Iteration431/407 e1,e2,e3 frozen float vectors treated as exact decimal inputs',
        'source_vectors': 'a,q,c,ETA frozen float arrays treated as exact decimal inputs'
    },
    'thresholds': {
        'mp80_vs_mp120_scaled_max': '1e-30',
        'assembly_reference_diagnostic_only': '2e-6',
        'physical_reference_diagnostic_only': '2e-5',
        'required_point_samples': 28*5*16*3*2,
        'all_finite': True
    },
    'observed': {
        'mp80_vs_mp120_scaled_max': mp.nstr(max_80_120, 30),
        'binary64_vs_mp120_scaled_max_any_geometry': mp.nstr(max_binary_mp120, 30),
        'binary64_vs_mp120_scaled_max_p': mp.nstr(max_binary_p_mp120, 30),
        'binary64_vs_mp120_scaled_max_affine_cc_aa': mp.nstr(max_binary_affine_mp120, 30),
        'binary64_vs_mp120_scaled_beta': mp.nstr(max_binary_beta_mp120, 30),
        'binary64_geometry_drift_material_relative_to_2e-6': material_assembly,
        'binary64_geometry_drift_material_relative_to_2e-5': material_physical,
        'point_sample_count': sample_count,
        'all_finite': all_finite,
        'worst_binary_vs_mp120_location': worst,
        'runtime_seconds': time.perf_counter() - start
    },
    'interpretation': [
        'PASS closes MP80/120 arithmetic for alpha,rho,beta,p,cc,aa given the frozen Iteration431/407 source vectors and basis.',
        'The binary64-vs-MP120 values are diagnostics of geometry arithmetic drift and do not alter thresholds.',
        'This gate does not certify arbitrary-precision reconstruction of e1,e2,e3 or upstream external/source vectors.',
        'Existing parent-MP and mass-node PASS results remain valid in their stated scope; this audit narrows the remaining continuous-precision boundary.'
    ],
    'next_gate_if_pass': 'if binary drift is subthreshold, freeze it as a representation diagnostic and separately audit/reconstruct the aligned transverse basis in MP before final full-F assembly; if material, port kinematic point generation itself to MP in the mass-node sampling chain before assembly',
    'next_gate_if_blocked': 'localize alpha/rho/beta/p/cc/aa at the first failing frozen coordinate without changing mass/z/phi/radial support or thresholds',
    'guardrails': [
        'NO_ACTIVE_RANK11_DUPLICATION',
        'NO_SUPPORT_REORDERING',
        'NO_BINARY_PARENT_RECAST_AS_MP',
        'FROZEN_BASIS_SCOPE_EXPLICIT',
        'NO_THRESHOLD_WEAKENING',
        'NO_MASS_STEP_CHANGE',
        'NO_PHI_ESCALATION',
        'NO_ZERO_FILL',
        'NO_PHYSICAL_DS_PROMOTION',
        'NO_ANSATZ003',
        'NO_FISHER_RESOURCES'
    ]
}
print(json.dumps(out, indent=2, sort_keys=True))
if not passed:
    raise SystemExit(2)
