#!/usr/bin/env python3
"""RQIR collision-safe post-447 class-3 actual-cut parent MP pilot.

This is the first direct 80/120-digit parent-arithmetic test using BOTH the
Iteration-368 timelike M fixture and actual near-cut momenta generated by the
Iteration-407/index-2 fixed-mass geometry.  It closes no physical D_s coordinate.

Prospectively frozen pilot samples:
- target double-double index 2 / class 3 / q^2=-1;
- all four signed mass corners u,v = +/-5e-6;
- z=-0.43, phi=0;
- finest already-frozen radial deformation h_r=5e-4, both signs;
- parent A1 h1=1e-4 and Q1/N1 h=3e-5 unchanged;
- 80 and 120 decimal digits;
- cross-precision threshold 1e-30.

The test recomputes Q0, Q1, A1=Asub(singleton) and the complete class-3 traced
stripped numerator directly in mpmath at the frozen physical p values.  It does
NOT obtain binary64 parent matrices and then recast them to mpmath.
"""
from __future__ import annotations
import contextlib, io, json, math, time
from pathlib import Path
import numpy as np
import mpmath as mp

ROOT=Path(__file__).resolve().parent
MP_LEVELS=(80,120)
MP_LIMIT=mp.mpf('1e-30')
PHYSICAL_REFERENCE=mp.mpf('2e-5')
MASS_R=5.0e-6
Z=-0.43
PHI=0.0
RADIAL_H=5.0e-4
H1=mp.mpf('1e-4')
HN1=mp.mpf('3e-5')

# Load the actual class-3/index-2 cut geometry and binary reference without
# executing the diagnostic loop of the manual collision-created 431 file.
p431=ROOT/'iteration431_channel2_cut_kinematic_h1_sensitivity.py'
t431=p431.read_text(); marker431='records=[]; max_delta=0.0; max_raderr=0.0'
if t431.count(marker431)!=1: raise SystemExit(('iteration431_boundary_drift',t431.count(marker431)))
C={'__name__':'post447_cut_parent431','__file__':str(p431)}
with contextlib.redirect_stdout(io.StringIO()): exec(compile(t431.split(marker431,1)[0],str(p431),'exec'),C,C)
if int(C['ch']['class_id'])!=3 or abs(float(C['q2'])+1.0)>1e-12: raise SystemExit('target_identity_drift')

# Load generalized arbitrary-precision geometry/A_finite infrastructure frozen
# by auto-research 436/438, but stop before its P0/POS result loop.
p438=ROOT/'iteration438_iter270_a_finite_multiprecision_core.py'
t438=p438.read_text(); marker438="subsets=[('s',),('a',),('b',),('s','a'),('s','b'),('a','b'),('s','a','b')]"
if t438.count(marker438)!=1: raise SystemExit(('iteration438_boundary_drift',t438.count(marker438)))
H={'__name__':'post447_parent438','__file__':str(p438)}
with contextlib.redirect_stdout(io.StringIO()): exec(compile(t438.split(marker438,1)[0],str(p438),'exec'),H,H)
P=H['P']; A_finite_mp=H['A_finite_mp']; mp_mat_from_np=H['mp_mat_from_np']; mp_vec_from_np=H['mp_vec_from_np']
norb_mp=P['norb_mp']; y_down_mp=P['y_down_mp']; ETA_mp=P['ETA_mp']

# Bind auto-research PASS records and new scope audit fail-closed.
R=ROOT.parent/'results'
for fn in ['iteration436_n1_multiprecision_closure_summary.json','iteration438_a_finite_multiprecision_core_summary.json','iteration440_acoef_asub_multiprecision_closure_summary.json','iteration446_postparent_contraction_precision.json','post447_cut_momentum_precision_scope_audit.json']:
    o=json.loads((R/fn).read_text())
    if o.get('scientific_gate_pass') is not True: raise SystemExit(('prerequisite_not_passed',fn))

M=C['M']; row=C['row']; a=np.asarray(C['a'],float); q=np.asarray(C['q'],float); kin=C['kin']; unit_from=C['unit_from']; stripped_h1=C['stripped_h1']; denominator_shifts=C['denominator_shifts']
ksum=C['ksum']; qs=np.asarray(M['s'][0],float); qp=np.asarray(ksum(('a','b')),float); kb=np.asarray(M['b'][0],float); ka=np.asarray(M['a'][0],float)
if float(np.max(np.abs(qs+qp)))>1e-14: raise SystemExit(('fixture_closure_drift',qs+qp))
Y0_BY_DPS={}


def scalar_scaled(a,b):
    return abs(a-b)/max(mp.mpf(1),abs(a),abs(b))


def q0_mp(p):
    return norb_mp([],[],p)**-1


def n1_mp(x,p):
    modes=[M[x]]
    fp=norb_mp([HN1],modes,p); fm=norb_mp([-HN1],modes,p)
    return (fp-fm)/(2*HN1)


def q1_mp(x,p):
    k=np.asarray(M[x][0],float)
    return -(q0_mp(p+k)*n1_mp(x,p)*q0_mp(p))


def a1_mp(x,p):
    modes=[M[x]]; K=np.asarray(M[x][0],float)
    plus=A_finite_mp([H1],modes,p,K); minus=A_finite_mp([-H1],modes,p,K)
    return (plus-minus)/(2*H1)


def mdot_mp(p):
    z=mp_vec_from_np(p)
    return (z.T*ETA_mp*z)[0]


def stripped_mp(p,dps):
    with mp.workdps(dps):
        y0=y_down_mp([],[])
        F=q0_mp(p+qp+qs)*a1_mp('s',p+qp)*q0_mp(p+qp)*y0
        S=q1_mp('a',p+kb)*a1_mp('b',p)*q0_mp(p)*y0
        amp=sum((F*S)[i,i] for i in range(4))
        den=mp.mpc(1)
        for sh in denominator_shifts(row):
            den*=mdot_mp(p+np.asarray(sh,float))
        z=amp*den
        return mp.nstr(mp.re(z),dps),mp.nstr(mp.im(z),dps)

samples=[]
for su in (-1.0,1.0):
    for sv in (-1.0,1.0):
        u=su*MASS_R; v=sv*MASS_R; alpha,rho,_,_=kin(u,v); vec=rho*unit_from(Z,PHI)
        for radial_sign in (-1.0,1.0):
            p=-a+alpha*q+(1.0+radial_sign*RADIAL_H)*vec
            samples.append({'u':u,'v':v,'radial_sign':radial_sign,'p':np.asarray(p,float)})

start=time.perf_counter(); rows=[]; mx=mp.mpf('0'); bmx=mp.mpf('0'); finite=True
for i,s in enumerate(samples):
    refs={}
    for dps in MP_LEVELS: refs[dps]=stripped_mp(s['p'],dps)
    with mp.workdps(150):
        z80=mp.mpc(mp.mpf(refs[80][0]),mp.mpf(refs[80][1])); z120=mp.mpc(mp.mpf(refs[120][0]),mp.mpf(refs[120][1]))
        cross=scalar_scaled(z80,z120); mx=max(mx,cross)
        zb=complex(stripped_h1(s['p'],1e-4)); zbm=mp.mpc(repr(float(zb.real)),repr(float(zb.imag)))
        bdiag=scalar_scaled(zbm,z120); bmx=max(bmx,bdiag)
        ok=bool(mp.isfinite(z120.real) and mp.isfinite(z120.imag) and np.isfinite(zb.real) and np.isfinite(zb.imag)); finite=finite and ok
        rows.append({'sample_index':i,'u':s['u'],'v':s['v'],'z':Z,'phi':PHI,'radial_h':RADIAL_H,'radial_sign':s['radial_sign'],'p':[float(x) for x in s['p']],
                     'mp80_re':refs[80][0],'mp80_im':refs[80][1],'mp120_re':refs[120][0],'mp120_im':refs[120][1],
                     'scaled_mp80_vs_mp120':mp.nstr(cross,30),'scaled_binary64_vs_mp120_diagnostic':mp.nstr(bdiag,30),'finite':ok})

passed=bool(len(rows)==8 and finite and mx<=MP_LIMIT)
material_binary=bool(bmx>PHYSICAL_REFERENCE)
result={
 'stage':'POST447_CLASS3_ACTUAL_CUT_PARENT_MP_PILOT__UNNUMBERED_COLLISION_SAFE',
 'classification':('PASS_CLASS3_ACTUAL_CUT_PARENT_MP80_MP120_PILOT__NON_PROMOTING' if passed else 'BLOCKED_CLASS3_ACTUAL_CUT_PARENT_MP_PILOT__NON_PROMOTING'),
 'scientific_gate_pass':passed,'promotes_physical_coordinate':False,'MODEL_READINESS':'24%','readiness_change_pp':0,
 'target':{'double_double_index':2,'class_id':3,'q_squared':-1.0},
 'scope':'ACTUAL_ITER407_NEAR_CUT_PARENT_ARITHMETIC_PILOT__FOUR_MASS_CORNERS_ONE_ANGULAR_POINT_FINEST_RADIAL_PAIR_ONLY',
 'frozen':{'mass_radius':MASS_R,'mass_corners':4,'z':Z,'phi':PHI,'radial_h':RADIAL_H,'radial_signs':[-1,1],'precision_digits':[80,120],'A1_h1':1e-4,'N1_h':3e-5,'M_fixture':'Iteration368 TIMELIKE M seed319'},
 'thresholds':{'scaled_mp80_vs_mp120_max':'1e-30','required_sample_count':8,'all_finite':True,'binary64_vs_mp120_physical_reference_diagnostic_only':'2e-5'},
 'observed':{'scaled_mp80_vs_mp120_max':mp.nstr(mx,30),'scaled_binary64_vs_mp120_max_diagnostic':mp.nstr(bmx,30),'binary64_drift_material_relative_to_2e-5_reference':material_binary,'sample_count':len(rows),'all_finite':finite,'runtime_seconds':time.perf_counter()-start},
 'rows':rows,
 'interpretation':'PASS would show that generalized parent MP arithmetic remains internally 80/120 stable on a prospectively frozen set of actual index-2 near-cut momenta with the real Iteration-368 M fixture. It is a pilot only: it does not close full phi/sample generation, radial Richardson, spectral algebra, mass differentiation, Iteration424, or D_s.',
 'next_gate_if_pass':'extend the same direct parent MP evaluation to all prospectively frozen phi/z/radial samples needed by the active index-2 fixed-mass F path, after raw-consumption of the independent spectral-algebra stage',
 'next_gate_if_blocked':'localize the failing Q0/Q1/A1 parent component at the same M,p,h without changing physics or thresholds',
 'guardrails':['NO_AUTHORITATIVE_ITERATION_NUMBER_REUSE','NO_BINARY_PARENT_RECAST_AS_MP','NO_PHYSICAL_DS_PROMOTION','NO_H_CHANGE','NO_MASS_NODE_CHANGE','NO_THRESHOLD_WEAKENING','NO_ANGULAR_GRID_ESCALATION','NO_ZERO_FILL','NO_ANSATZ003','NO_FISHER_RESOURCES']
}
print(json.dumps(result,indent=2,sort_keys=True))
if not passed: raise SystemExit(2)
