#!/usr/bin/env python3
"""RQIR Candidate Gravity Iteration 186.

Compute the full QG-NL-EXP-001 lambda tangent at lambda=1 on the six frozen
null-soft TT rows, using the exact multilinear covariant Box calculus frozen in
Iteration 185.  For

  S_NL ~ int sqrt(-g) G_mn F(Box) R^mn,
  F(Box)=(exp(-lambda Box)-1)/Box,

we have d_lambda F|_1 = -exp(-Box).  On the frozen TT external legs every
linear scalar curvature vanishes.  Hence the cubic soft2 tangent of the scalar
piece -(1/2) R dF R vanishes, including operator/Frechet insertions, and the
full scoped lambda tangent is generated by

  R_mn [-exp(-Box)] R^mn
    = sum_n (-1)^(n+1)/n! R_mn Box^n R^mn.

The Box recursion is action-level and therefore contains connection,
inverse-metric, and operator/Frechet variations automatically.
"""
from pathlib import Path
import contextlib, io, json, math, runpy
import numpy as np

with contextlib.redirect_stdout(io.StringIO()):
    base = runpy.run_path('analysis/c5_local_quadratic_soft2_completion_iteration185.py')
ETA=base['ETA']; QS=base['QS']; dot=base['dot']; prod=base['prod']
row_kin=base['row_kin']; build_geom=base['build_geom']; box_rank2=base['box_rank2']
HS=base['HS']

NMAX=14

def action_coeffs_alln(ks,es,nmax=NMAX):
    gi,G,Ric,sqrtg=build_geom(ks,es)
    gi2=prod(gi,gi,op=lambda A,B:np.einsum('ma,nb->mnab',A,B))
    vals=[]; T=Ric
    full=(1<<len(ks))-1
    for _n in range(nmax+1):
        RT=prod(Ric,T,op=lambda A,B:np.einsum('mn,ab->mnab',A,B))
        contr=prod(gi2,RT,op=lambda A,B:np.einsum('mnab,mnab',A,B))
        vals.append(prod(sqrtg,contr).get(full,0).real)
        T=box_rank2(T,ks,gi,G)
    return np.array(vals,float)

def soft2_all(i,nmax=NMAX):
    f0=action_coeffs_alln(*row_kin(i,0),nmax)
    c=[]
    for h in HS:
        c.append((action_coeffs_alln(*row_kin(i,h),nmax)+
                  action_coeffs_alln(*row_kin(i,-h),nmax)-2*f0)/(2*h*h))
    c=np.array(c)
    r1=(4*c[1:]-c[:-1])/3
    r2=(16*r1[1:]-r1[:-1])/15
    return r2[-1],np.abs(r2[-1]-r2[-2])

cols=np.zeros((6,NMAX+1)); errs=np.zeros_like(cols)
for i in range(6):
    cols[i],errs[i]=soft2_all(i)
weights=np.array([(-1)**(n+1)/math.factorial(n) for n in range(NMAX+1)],float)
partials=np.array([cols[:,:m+1]@weights[:m+1] for m in range(NMAX+1)])
S_nl=partials[-1]

# Frozen Iteration-185 K2-preserving local compensation, already expressed in
# the same six soft2 row coordinates.
S_local=np.array([0.6749106618554018,0.09041841732117784,1.6058813167372494,
                  -0.8456710923733669,-0.0817908524675452,0.04041297883593838])
S_cond=S_nl+S_local

# Frozen Iteration-178 exact zero-K2 local curvature-cubic span.
r0=np.array([-1.6411697071822275,0.06385882717014456,0.8548821188463769,
             -0.17055215671317986,-0.3261917310634991,-0.1655609264695088])
x=np.array([dot(q,q) for q in QS],float)
V4=np.column_stack([r0,-x*r0,x*x*r0,-x**3*r0])
coef=np.linalg.lstsq(V4,S_cond,rcond=None)[0]
res=S_cond-V4@coef
envelope=5.2625580e-6

# Internal provenance checks against the curated Iteration-185 action columns.
expected={
  2:np.array([-1.116518384913729,-0.013875145770453961,-1.6820857577385013,0.2756448325165249,0.26633541804099714,0.27289104445501416]),
  3:np.array([0.7133600699918851,0.0017605281520687176,1.0529592750292909,-0.11112973689055448,-0.2235239287182969,-0.14597119757804206]),
  4:np.array([-0.4308356612729251,0.0013520156067859145,-0.627497661780086,0.043104686244338386,0.1618211491758664,0.06744072950231582])}
repro=max(float(np.max(np.abs(cols[:,n]-v))) for n,v in expected.items())

tail={f'N{n}_vs_N{n-1}':float(np.max(np.abs(partials[n]-partials[n-1])))
      for n in range(NMAX,9,-1)}
out={
 'iteration':186,
 'model_readiness_percent':24,
 'scope':'six frozen null-soft TT rows; QG-NL-EXP-001 lambda tangent at lambda=1 conditioned by exact K2 calibration',
 'parent_action':'sqrt(-g)[R + G_mn F(Box) R^mn], F=(exp(-lambda Box)-1)/Box',
 'lambda_derivative':'d_lambda F|_1=-exp(-Box)',
 'scalar_piece_status':'EXACT_PROTOCOL_ZERO_AT_CUBIC_SOFT2_BECAUSE_R_LINEAR_IS_ZERO_ON_ALL_TT_EXTERNAL_LEGS',
 'series_nmax':NMAX,
 'series_tail_maxabs':tail,
 'max_local_column_reproduction_error_n2_to_n4':repro,
 'max_soft2_extrapolation_error_by_n':np.max(errs,axis=0).tolist(),
 'nonlocal_lambda_soft2':S_nl.tolist(),
 'local_K2_compensation_soft2':S_local.tolist(),
 'conditioned_nonlocal_soft2':S_cond.tolist(),
 'zero_K2_local_curvature_cubic_rank':int(np.linalg.matrix_rank(V4,tol=1e-10)),
 'projection_coefficients_on_V4':coef.tolist(),
 'conditioned_residual':res.tolist(),
 'conditioned_residual_l2':float(np.linalg.norm(res)),
 'conditioned_residual_maxabs':float(np.max(np.abs(res))),
 'frozen_envelope':envelope,
 'l2_margin_over_envelope':float(np.linalg.norm(res)/envelope),
 'classification':{
   'QG_NL_EXP_001_lambda_soft2':'RESOLVED_INDEPENDENT_COMPARATOR_DIRECTION',
   'relation_to_local_C5':'NOT_IN_ZERO_K2_LOCAL_RANK4_SPAN_ON_FROZEN_ROWS',
   'novelty_certificate':'NONE_THIS_IS_A_COMPARATOR_DIRECTION_NOT_A_CANDIDATE_RESIDUAL',
   'ANSATZ_003':'NOT_CREATED','Fisher_resources':'FORBIDDEN'},
 'retained_results':[
   'NL-NG-005 — FULL_QG_NL_EXP_001_LAMBDA_SOFT2_TANGENT_IS_RESOLVABLE_AFTER_EXACT_K2_COMPENSATION',
   'REL-NG-004 — K2_PRESERVING_NONLOCAL_DIRECTION_SURVIVES_THE_FROZEN_ZERO_K2_LOCAL_C5_RANK4_QUOTIENT',
   'NG-FUNNEL-040 — A_RESOLVED_NONLOCAL_COMPARATOR_DIRECTION_IS_NUISANCE_AUTHORITY_NOT_CANDIDATE_NOVELTY'],
 'readiness_change':'unchanged at 24%: the fixed nonlocal comparator is now resolved in the scoped relation space, but C3 ordered completion and real-time/source-completed asymptotic-safety remain BLOCKED and no candidate residual exists.'}
Path('results/nonlocal_lambda_soft2_quotient_iteration186.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n',encoding='utf-8')
print(json.dumps(out,indent=2,sort_keys=True))
