"""RQIR Toy011 / Iteration 052: local nearest-neighbor source embedding.

Two tasks:
1. Audit the accepted Toy009 source for spatial locality by transforming its
   fixed Hamiltonian H=diag(1,2,3,4,6) to the eigenbasis of the radius operator.
2. Construct a genuinely nearest-neighbor five-site Jacobi-chain family with
   the same exact spectrum and Toy009 radii, then jointly scan the local source
   spectral weights and NP3 calibration geometry.

A Jacobi chain is generated by Lanczos tridiagonalization of diag(E) from a
positive cyclic vector q0.  This gives an exactly tridiagonal site Hamiltonian,
while the site/radius operator is diagonal by construction.  The scan varies
q0, the second probe position and six nonzero calibration phases.

Selection is Pareto-oriented: retain a response-oriented point with smin>=8e-4
and a conditioning-oriented composite point.  No claim of global optimality.
"""
from __future__ import annotations

import math
import numpy as np

D = 5
E = np.array([1., 2., 3., 4., 6.])
H = np.diag(E).astype(complex)
EPS = 0.08
N_SCAN = 12000
SEED = 20260902

# Current practical Toy009 / Iteration-011 geometry used only as a comparison
# baseline, not imposed on the local-source scan.
Y1_BASE = -3.7766873836695947
TIMES_BASE = np.array([0., 3.09855988, 3.45849306, 2.93830159,
                       4.13016958, 4.84480925, 4.99085067])


def herm_vec(a):
    out = [a[i, i].real for i in range(D)]
    for i in range(D):
        for j in range(i + 1, D):
            out += [np.sqrt(2.0) * a[i, j].real,
                    np.sqrt(2.0) * a[i, j].imag]
    return np.asarray(out, float)


def mat(v):
    a = np.zeros((D, D), complex)
    k = 0
    for i in range(D):
        a[i, i] = v[k]
        k += 1
    for i in range(D):
        for j in range(i + 1, D):
            a[i, j] = (v[k] + 1j * v[k + 1]) / np.sqrt(2.0)
            a[j, i] = a[i, j].conjugate()
            k += 2
    return a


def evolve(a, t):
    return a * np.exp(1j * (E[:, None] - E[None, :]) * t)


def sym(a, b):
    return (a @ b + b @ a) / 2.0


def harmonic(delta, readout, pump, n):
    rw = np.zeros_like(readout, complex)
    for i in range(D):
        for j in range(D):
            if int(round(E[i] - E[j])) == n:
                rw[i, j] = readout[i, j]
    return 2.0 * np.trace(delta @ ((rw @ pump - pump @ rw) / (2j)))


def seff(z2, z4):
    p2, p4 = abs(z2)**2, abs(z4)**2
    return float(4.0 * p2 * p4 / (p2 + p4)) if p2 + p4 > 0 else 0.0


def toy009_geometry():
    rng = np.random.default_rng(314159)
    for _ in range(812):
        x = rng.normal(size=(D, D))
        braw = (x + x.T) / 2.0
    ev = np.linalg.eigvalsh(braw)
    bpos = braw + (-ev.min() + 1.0) * np.eye(D)
    vals, v = np.linalg.eigh(bpos)
    scale = float(vals.max())
    radii_unsorted = scale / vals
    order = np.argsort(radii_unsorted)
    radii = radii_unsorted[order]
    v_sorted = v[:, order]
    return radii, v_sorted


RADII, V009_SORTED = toy009_geometry()


def old_locality_audit():
    h_radius = V009_SORTED.T @ np.diag(E) @ V009_SORTED
    off = h_radius.copy()
    np.fill_diagonal(off, 0.0)
    nn = np.zeros_like(off)
    for i in range(D - 1):
        nn[i, i + 1] = off[i, i + 1]
        nn[i + 1, i] = off[i + 1, i]
    nonlocal_part = off - nn
    frac = float(np.linalg.norm(nonlocal_part)**2 / np.linalg.norm(off)**2)
    trunc = h_radius.copy()
    for i in range(D):
        for j in range(D):
            if i != j and abs(i - j) > 1:
                trunc[i, j] = 0.0
    rel = float(np.linalg.norm(h_radius - trunc) / np.linalg.norm(h_radius))
    return h_radius, frac, rel, np.linalg.eigvalsh(trunc)


def lanczos_q(q0):
    q = np.asarray(q0, float)
    q /= np.linalg.norm(q)
    qprev = np.zeros(D)
    beta_prev = 0.0
    cols = []
    a = np.diag(E)
    for j in range(D):
        cols.append(q.copy())
        z = a @ q - beta_prev * qprev
        alpha = float(q @ z)
        z -= alpha * q
        for qi in cols:
            z -= qi * (qi @ z)
        if j < D - 1:
            beta = float(np.linalg.norm(z))
            if beta < 1e-10:
                return None
            qprev = q
            q = z / beta
            beta_prev = beta
    return np.column_stack(cols)


def operators(qbasis, y1):
    p0 = (qbasis @ np.diag(1.0 / RADII) @ qbasis.T).astype(complex)
    p1 = (qbasis @ np.diag(1.0 / np.abs(RADII - y1)) @ qbasis.T).astype(complex)
    g0 = (qbasis @ np.diag(1.0 / RADII**2) @ qbasis.T).astype(complex)
    return p0, p1, g0


def calibration_rows(p0, p1, times):
    tr = float(times[2])
    p = [p0, p1]
    rows = [herm_vec(np.eye(D)), herm_vec(H)]
    for k in (0, 1):
        for t in times:
            rows.append(herm_vec(evolve(p[k], float(t))))
    rows.append(herm_vec(sym(evolve(p0, tr), p0)))
    extra = [
        (0, 1, times[1]), (1, 1, times[5]), (1, 0, tr),
        (0, 1, tr), (1, 0, times[3]), (0, 0, times[6]),
        (0, 1, times[6]),
    ]
    for k, l, t in extra:
        rows.append(herm_vec(sym(evolve(p[k], float(t)), p[l])))
    return np.vstack(rows)


def evaluate(q0, y1, times):
    qb = lanczos_q(q0)
    if qb is None:
        return None
    p0, p1, g0 = operators(qb, y1)
    a = calibration_rows(p0, p1, times)
    an = a / np.linalg.norm(a, axis=1, keepdims=True)
    _u, sv, vh = np.linalg.svd(an, full_matrices=True)
    if sv[-1] <= 1e-14:
        return None
    d0 = mat(vh[-1])
    d0 /= np.max(np.abs(np.linalg.eigvalsh(d0)))
    delta = 2.0 * EPS * d0
    h2 = harmonic(delta, p0, p0, 2)
    h4 = harmonic(delta, p0, p0, 4)
    g2 = harmonic(delta, g0, p0, 2)
    g4 = harmonic(delta, g0, p0, 4)
    return {
        "Q": qb,
        "d0": d0,
        "A": a,
        "smin": float(sv[-1]),
        "cond": float(sv[0] / sv[-1]),
        "D1": seff(h2, h4),
        "D2": seff(g2, g4),
        "H2": h2, "H4": h4, "G2": g2, "G4": g4,
        "q0": np.asarray(q0, float) / np.linalg.norm(q0),
        "y1": float(y1), "times": np.asarray(times, float).copy(),
    }


def baseline_009():
    # Reconstruct the current Iteration-011 Toy009 source in energy basis.
    # V009_SORTED uses sorted radii columns; functionals are invariant to that
    # column permutation as long as the radii are permuted consistently.
    p0 = (V009_SORTED @ np.diag(1.0 / RADII) @ V009_SORTED.T).astype(complex)
    p1 = (V009_SORTED @ np.diag(1.0 / np.abs(RADII - Y1_BASE)) @ V009_SORTED.T).astype(complex)
    g0 = (V009_SORTED @ np.diag(1.0 / RADII**2) @ V009_SORTED.T).astype(complex)
    a = calibration_rows(p0, p1, TIMES_BASE)
    an = a / np.linalg.norm(a, axis=1, keepdims=True)
    _u, sv, vh = np.linalg.svd(an, full_matrices=True)
    d0 = mat(vh[-1])
    d0 /= np.max(np.abs(np.linalg.eigvalsh(d0)))
    delta = 2.0 * EPS * d0
    h2 = harmonic(delta, p0, p0, 2)
    h4 = harmonic(delta, p0, p0, 4)
    g2 = harmonic(delta, g0, p0, 2)
    g4 = harmonic(delta, g0, p0, 4)
    return float(sv[-1]), float(sv[0]/sv[-1]), seff(h2, h4), seff(g2, g4)


def exact_checks(candidate):
    rho0 = np.eye(D) / D
    rp = rho0 + EPS * candidate["d0"]
    rm = rho0 - EPS * candidate["d0"]
    residual = float(np.max(np.abs(candidate["A"] @ herm_vec(rp - rm))))
    return np.linalg.eigvalsh(rp), np.linalg.eigvalsh(rm), residual


def main():
    hrad, nonfrac, reltrunc, trunc_e = old_locality_audit()
    print("Toy009 H in sorted radius basis\n", hrad)
    print("non-nearest offdiag power fraction", nonfrac)
    print("nearest-neighbor trunc relative H error", reltrunc)
    print("nearest-neighbor trunc eigenvalues", trunc_e)
    assert abs(nonfrac - 0.6446219291847903) < 2e-12
    assert abs(reltrunc - 0.3689304260922054) < 2e-12

    b_smin, b_cond, b_d1, b_d2 = baseline_009()
    print("Iteration011 Toy009 baseline", b_smin, b_cond, b_d1, b_d2)
    assert abs(b_smin - 0.001999540405542146) < 3e-12
    assert abs(b_cond - 2313.0464205969242) < 3e-8

    rng = np.random.default_rng(SEED)
    best_response = None  # maximize D2 subject to smin>=8e-4
    best_composite = None # maximize smin*sqrt(D2/baseline)

    for trial in range(N_SCAN):
        q0 = np.exp(rng.normal(0.0, 0.8, size=D))
        q0 /= np.linalg.norm(q0)
        y1 = -rng.uniform(1.0, 12.0)
        times = np.r_[0.0, rng.uniform(0.0, 2.0 * math.pi, 6)]
        r = evaluate(q0, y1, times)
        if r is None:
            continue
        if r["smin"] >= 8e-4:
            if best_response is None or r["D2"] > best_response[1]["D2"]:
                best_response = (trial, r)
        score = (r["smin"] / 0.001) * math.sqrt(r["D2"] / b_d2)
        if best_composite is None or score > best_composite[0]:
            best_composite = (score, trial, r)

    assert best_response is not None and best_composite is not None
    tr, rr = best_response
    _score, tc, rc = best_composite
    print("response-oriented trial", tr, rr)
    print("conditioning/composite trial", tc, rc)

    # Deterministic scan regressions.
    assert tr == 6304
    assert abs(rr["smin"] - 0.0009922486046052387) < 3e-14
    assert abs(rr["cond"] - 4701.82888980337) < 3e-7
    assert abs(rr["D1"] / b_d1 - 0.12204323685157116) < 3e-10
    assert abs(rr["D2"] / b_d2 - 0.1558200714788344) < 3e-10

    assert tc == 3811
    assert abs(rc["smin"] - 0.0018421882323268282) < 3e-14
    assert abs(rc["cond"] - 2540.424823550273) < 3e-7
    assert abs(rc["D1"] / b_d1 - 0.05418773988879441) < 3e-10
    assert abs(rc["D2"] / b_d2 - 0.08163415302222209) < 3e-10

    for name, cand in (("response", rr), ("conditioning", rc)):
        hp, hm, residual = exact_checks(cand)
        tsite = cand["Q"].T @ np.diag(E) @ cand["Q"]
        far = tsite.copy()
        for i in range(D):
            for j in range(D):
                if i == j or abs(i-j) == 1:
                    far[i,j] = 0.0
        print(name, "site Hamiltonian\n", tsite)
        print(name, "state minima", hp.min(), hm.min(), "exact residual", residual)
        assert np.linalg.norm(far) < 2e-12
        assert np.max(np.abs(np.linalg.eigvalsh(tsite) - E)) < 2e-12
        assert hp.min() > 0 and hm.min() > 0
        assert residual < 1e-12


if __name__ == "__main__":
    main()
